/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'unity-file-tools.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./unity-file-tools.android-arm64.node')
          } else {
            nativeBinding = require('unity-file-tools-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'unity-file-tools.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./unity-file-tools.android-arm-eabi.node')
          } else {
            nativeBinding = require('unity-file-tools-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'unity-file-tools.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./unity-file-tools.win32-x64-msvc.node')
          } else {
            nativeBinding = require('unity-file-tools-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'unity-file-tools.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./unity-file-tools.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('unity-file-tools-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'unity-file-tools.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./unity-file-tools.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('unity-file-tools-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'unity-file-tools.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./unity-file-tools.darwin-universal.node')
      } else {
        nativeBinding = require('unity-file-tools-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'unity-file-tools.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./unity-file-tools.darwin-x64.node')
          } else {
            nativeBinding = require('unity-file-tools-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'unity-file-tools.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./unity-file-tools.darwin-arm64.node')
          } else {
            nativeBinding = require('unity-file-tools-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'unity-file-tools.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./unity-file-tools.freebsd-x64.node')
      } else {
        nativeBinding = require('unity-file-tools-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'unity-file-tools.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unity-file-tools.linux-x64-musl.node')
            } else {
              nativeBinding = require('unity-file-tools-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'unity-file-tools.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unity-file-tools.linux-x64-gnu.node')
            } else {
              nativeBinding = require('unity-file-tools-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'unity-file-tools.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unity-file-tools.linux-arm64-musl.node')
            } else {
              nativeBinding = require('unity-file-tools-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'unity-file-tools.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unity-file-tools.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('unity-file-tools-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'unity-file-tools.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unity-file-tools.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('unity-file-tools-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'unity-file-tools.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unity-file-tools.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('unity-file-tools-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'unity-file-tools.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unity-file-tools.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('unity-file-tools-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'unity-file-tools.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./unity-file-tools.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('unity-file-tools-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'unity-file-tools.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./unity-file-tools.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('unity-file-tools-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { ChunkType, extractDllTypes, extractDllFields, extractCsharpTypes, buildTypeRegistry, extractSerializedFields, Scanner, Indexer, EmbeddingGenerator, walkProjectFiles, grepProject, buildGuidCache, buildPackageGuidCache, getVersion, isNativeAvailable } = nativeBinding

module.exports.ChunkType = ChunkType
module.exports.extractDllTypes = extractDllTypes
module.exports.extractDllFields = extractDllFields
module.exports.extractCsharpTypes = extractCsharpTypes
module.exports.buildTypeRegistry = buildTypeRegistry
module.exports.extractSerializedFields = extractSerializedFields
module.exports.Scanner = Scanner
module.exports.Indexer = Indexer
module.exports.EmbeddingGenerator = EmbeddingGenerator
module.exports.walkProjectFiles = walkProjectFiles
module.exports.grepProject = grepProject
module.exports.buildGuidCache = buildGuidCache
module.exports.buildPackageGuidCache = buildPackageGuidCache
module.exports.getVersion = getVersion
module.exports.isNativeAvailable = isNativeAvailable
