/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Basic GameObject information */
export interface GameObject {
  name: string
  fileId: string
  active: boolean
  matchScore?: number | undefined
}
/** Component information */
export interface Component {
  type: string
  classId: number
  fileId: string
  scriptPath?: string | undefined
  scriptGuid?: string | undefined
  scriptName?: string | undefined
  properties?: Record<string, any> | undefined
}
/** GameObject with detailed component information */
export interface GameObjectDetail {
  name: string
  fileId: string
  active: boolean
  tag: string
  layer: number
  components: Array<Component>
  children?: string[] | undefined
  parentTransformId?: string | undefined
}
/** PrefabInstance information */
export interface PrefabInstanceInfo {
  name: string
  fileId: string
  sourceGuid: string
  sourcePrefab?: string | undefined
  modificationsCount: number
}
/** Union result from find_by_name: either a GameObject or PrefabInstance */
export interface FindResult {
  name: string
  fileId: string
  resultType: string
  active?: boolean | undefined
  matchScore?: number | undefined
  sourceGuid?: string | undefined
  sourcePrefab?: string | undefined
  modificationsCount?: number | undefined
}
/** Full scene inspection result */
export interface SceneInspection {
  file: string
  count: number
  gameobjects: Array<GameObjectDetail>
  prefabInstances?: PrefabInstanceInfo[] | undefined
}
/** Options for scanning */
export interface ScanOptions {
  verbose?: boolean | undefined
}
/** Options for inspecting */
export interface InspectOptions {
  file: string
  identifier?: string | undefined
  includeProperties?: boolean | undefined
  verbose?: boolean | undefined
}
/** Pagination options for inspect_all */
export interface PaginationOptions {
  file: string
  includeProperties?: boolean | undefined
  verbose?: boolean | undefined
  pageSize?: number | undefined
  cursor?: number | undefined
  maxDepth?: number | undefined
}
/** Paginated inspection result */
export interface PaginatedInspection {
  file: string
  total: number
  cursor: number
  nextCursor?: number | undefined
  truncated: boolean
  pageSize: number
  gameobjects: Array<GameObjectDetail>
  prefabInstances?: PrefabInstanceInfo[] | undefined
}
/** Chunk types for indexing */
export const enum ChunkType {
  Prose = 'Prose',
  Code = 'Code',
  Api = 'Api',
  Example = 'Example'
}
/** Chunk metadata */
export interface ChunkMetadata {
  filePath: string
  section?: string | undefined
  language?: string | undefined
  unityClass?: string | undefined
  unityMethod?: string | undefined
}
/** A chunk of indexed content */
export interface Chunk {
  id: string
  content: string
  tokens: number
  type: ChunkType
  metadata: ChunkMetadata
}
/** Result of indexing operation */
export interface IndexResult {
  chunksIndexed: number
  totalTokens: number
  filesProcessed: number
  elapsedMs: number
}
/** Search result from index */
export interface SearchResult {
  id: string
  content: string
  score: number
  metadata: ChunkMetadata
}
/** Get the version of the native module */
export declare function getVersion(): string
/** Check if the native module is available */
export declare function isNativeAvailable(): boolean
/** High-performance Unity scene/prefab scanner */
export declare class Scanner {
  constructor()
  /** Add a hierarchy provider class ID (Transform-like components). */
  addHierarchyProvider(classId: number): void
  /** Add a script container class ID (MonoBehaviour-like components). */
  addScriptContainer(classId: number): void
  /** Set project root for GUID resolution */
  setProjectRoot(path: string): void
  /** Scan scene for basic GameObject information */
  scanSceneMinimal(file: string): Array<GameObject>
  /** Scan scene with component information */
  scanSceneWithComponents(file: string, options?: ScanOptions | undefined | null): Array<any>
  /** Find GameObjects and PrefabInstances by name pattern */
  findByName(file: string, pattern: string, fuzzy: boolean): Array<FindResult>
  /** Inspect a specific GameObject */
  inspect(options: InspectOptions): any | null
  /** Inspect entire file */
  inspectAll(file: string, includeProperties: boolean, verbose: boolean): SceneInspection
  /** Inspect entire file with pagination support */
  inspectAllPaginated(options: PaginationOptions): PaginatedInspection
}
/** High-performance documentation indexer */
export declare class Indexer {
  constructor()
  /** Index a single file */
  indexFile(path: string): IndexResult
  /** Index a directory of files */
  indexDirectory(path: string): IndexResult
  /** Search the index */
  search(query: string): Array<SearchResult>
  /** Clear the index */
  clear(): void
  /** Get index statistics */
  stats(): any
}
/**
 * Local CPU embedding generator using all-MiniLM-L6-v2 (384 dims).
 * Wraps fastembed-rs / ONNX Runtime. Model auto-downloads on first use
 * and is cached at ~/.claude/unity-agentic-tools/models/.
 */
export declare class EmbeddingGenerator {
  constructor()
  /** Generate embedding for a single text. Returns a Vec<f64> (384 dims). */
  generate(text: string): Array<number>
  /** Generate embeddings for a batch of texts. Returns Vec<Vec<f64>>. */
  generateBatch(texts: Array<string>): Array<Array<number>>
}
